/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mo_badawy
 */

import java .sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing .JOptionPane;
import javax.swing.table.DefaultTableModel;
public class hotle00 extends javax.swing.JFrame {

    /**
     * Creates new form hotle00
     */
    public hotle00() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jperiod = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jIno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jItype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jlable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFname = new javax.swing.JTextField();
        jLname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRoomNo = new javax.swing.JTextField();
        jroomtype = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jtotal = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jShowBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jNationalty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_no", "first_name", "last_name", "id_type", "addrass", "nationalty", "phone", "gender", "Email", "ID_room", "Room no."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jperiod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jperiod.setEnabled(false);
        jperiod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jperiodActionPerformed(evt);
            }
        });

        jTextField10.setEnabled(false);

        jTextField14.setEnabled(false);

        jLabel27.setText("%");

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderActionPerformed(evt);
            }
        });

        jLabel8.setText("ID Number");

        jLabel28.setText("Room Number");

        jLabel10.setText("ID Type");

        jItype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver license", "National ID card", "passport" }));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guest Information");
        jLabel1.setAutoscrolls(true);

        jlable.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address");

        jLabel5.setText("Nationality");

        jLabel6.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Rate Information");

        jLabel13.setText("Date In");

        jLabel14.setText("Room Type");

        jLabel15.setText("No. of Days");

        jLabel16.setText("No. of Childrens");

        jRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomNoActionPerformed(evt);
            }
        });

        jroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        jroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jroomtypeActionPerformed(evt);
            }
        });

        jLabel18.setText("Date Out");

        jLabel19.setText("Rate / Period");

        jLabel20.setText("Total Charges");

        jLabel21.setText("Other Charges");

        jLabel22.setText("Sub Total");

        jLabel23.setText("Discount");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTextField11.setEnabled(false);

        jtotal.setEnabled(false);
        jtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotalActionPerformed(evt);
            }
        });

        jLabel24.setText("Total");

        jLabel25.setText("Amount Paid");

        jLabel26.setText("balance");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jShowBtn.setText("Select");
        jShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowBtnActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Updatte");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Calculation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Room");

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addGap(2, 2, 2))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Email");

        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room_no", "date_in", "room_type", "Date_out", "no_day", "no_chiled"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setText("Phone");

        jPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Room", "Rate/Period", "Totale Charges", "outher totale", "Sub Total", "Descount", "Total", "Amount paid", "balance"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jNationalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNationaltyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jItype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jIno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField14)
                                                .addGap(20, 20, 20))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField10)
                                            .addComponent(jperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jroomtype, 0, 119, Short.MAX_VALUE)
                                            .addComponent(jSpinner2)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRoomNo)
                                            .addComponent(jTextField2))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jNationalty, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jItype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jIno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jAddress)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNationalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addGap(1, 1, 1)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jroomtype)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomNoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jRoomNoActionPerformed

    private void jGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jGenderActionPerformed

    private void jShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowBtnActionPerformed
         try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from guest_information");
            
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("id_carde");
             dm.addColumn("first_name");
             dm.addColumn("last_name");
             dm.addColumn("ID_Type");
             dm.addColumn("address");
             dm.addColumn("Nationalty");
             dm.addColumn("Phone");
             dm.addColumn("gender");
             dm.addColumn("email");
             dm.addColumn("ID_Room");
             dm.addColumn("Room_no.");
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8),set.getString(9),set.getString(10),set.getString(11)};
                dm.addRow(r);   
            }
            jTable1.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
         try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from room_information");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("Room_no");
             dm.addColumn("date_in");
             dm.addColumn("room_type");
             dm.addColumn("Date_out");
             dm.addColumn("no_day");
             dm.addColumn("no_chiled");
             
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);   
            }
            jTable2.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
          try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from rate_information");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("ID_room");
             dm.addColumn("rate_period");
             dm.addColumn("total_charges");
             dm.addColumn("outher_charges");
             dm.addColumn("sub_total");
             dm.addColumn("discount");
             dm.addColumn("total");
             dm.addColumn("amount_paid");
             dm.addColumn("balance");
             
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8),set.getString(9)};
                dm.addRow(r);   
            }
            jTable3.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
        
    }//GEN-LAST:event_jShowBtnActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("insert into rate_information(ID_room,rate_period,total_charges,outher_charges,sub_total,discount,total,amount_paid,balance) values(?,?,?,?,?,?,?,?,?)");
          
        String ID_Room = jTextField1.getText();
        String rate_period = jperiod.getText();
        String total_charges = jTextField10.getText();
        String outher_charges = jTextField8.getText();
        String sub_total = jTextField14.getText();            
        String discount = jTextField15.getText();
        String total = jtotal.getText();
        String amount_paid = jTextField13.getText();
        String balance = jTextField11.getText();
        
        
        
        
        
        stmt.setString(1, ID_Room);
        stmt.setString(2, rate_period);
        stmt.setString(3, total_charges);
        stmt.setString(4, outher_charges);
        stmt.setString(5, sub_total);
        stmt.setString(6, discount);
        stmt.setString(7, total);
        stmt.setString(8, amount_paid);    
        stmt.setString(9, balance);
        
        
        stmt.executeUpdate();
        //JOptionPane.showMessageDialog(this, "IS DONE");
        
        //jTextField1.setText("");
        jperiod.setText("");
        jTextField10.setText("");
        jTextField8.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jtotal.setText("");
        jTextField13.setText("");
        jTextField11.setText("");
        
        
            jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
        
        
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("insert into room_information(Room_no,date_in,room_type,Date_out,no_day,no_chiled) values(?,?,?,?,?,?)");
            
           /* try{
            jSpinner1.commitEdit();
            jSpinner2.commitEdit();
        }
        catch(java.text.ParseException e){}
           */
           double noday = (int) jSpinner1.getValue();
           double noch = (int) jSpinner2.getValue();
           String str = Double.toString(noday);
           String str1 = Double.toString(noch);
        String Room_no = jRoomNo.getText();
        String date_in = jTextField2.getText();
        String room_type = (String) jroomtype.getSelectedItem();
        String Date_out =  jTextField3.getText();           
        String no_day = str ;
        String no_chiled = str1 ;
        
         
        
        stmt.setString(1, Room_no);
        stmt.setString(2, date_in);
        stmt.setString(3, room_type);
        stmt.setString(4, Date_out);
        stmt.setString(5, no_day);
        stmt.setString(6, no_chiled);
           
        
        stmt.executeUpdate();
        //JOptionPane.showMessageDialog(this, "IS DONE");
        
        //jRoomNo.setText("");
        jTextField2.setText("");
        jroomtype.setSelectedItem("");
        jTextField3.setText("");
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
        
        
        
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("insert into guest_information(id_no,first_name,last_name,id_type,addrass,nationalty,phone,gender,Email,ID_room,Room_no) values(?,?,?,?,?,?,?,?,?,?,?)");
            
        String id = jIno.getText();
        String first_name = jFname.getText();
        String last_name = jLname.getText();
        String ID_Type =  (String) jItype.getSelectedItem();            
        String address = jAddress.getText();
        String Nationalty = jNationalty.getText();
        String Phone = jPhone.getText();
        String gender = (String) jGender.getSelectedItem();
        String email = jEmail.getText();
        String ID_Room = jTextField1.getText();
        String Room_no = jRoomNo.getText(); 
        
        stmt.setString(1, id);
        stmt.setString(2, first_name);
        stmt.setString(3, last_name);
        stmt.setString(4, ID_Type);
        stmt.setString(5, address);
        stmt.setString(6, Nationalty);
        stmt.setString(7, Phone);    
        stmt.setString(8, gender);
        stmt.setString(9, email);
        stmt.setString(10, ID_Room);    
        stmt.setString(11, Room_no);
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "IS DONE");
        
        jIno.setText("");
        jFname.setText("");
        jLname.setText("");
        jItype.setSelectedItem("");
        jAddress.setText("");
        jNationalty.setText("");
        jPhone.setText("");
        jGender.setSelectedItem("");
        jTextField1.setText("");
        jEmail.setText("");
        jRoomNo.setText("");
        
            jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotalActionPerformed

    private void jperiodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jperiodActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jperiodActionPerformed

    private void jroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jroomtypeActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jroomtypeActionPerformed

    private void jPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row_num = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(row_num, 0 ).toString();
        String first_name = jTable1.getValueAt(row_num, 1 ).toString();
        String last_name = jTable1.getValueAt(row_num, 2 ).toString();
        String ID_Type = jTable1.getValueAt(row_num, 3 ).toString();
        String address = jTable1.getValueAt(row_num, 4 ).toString();
        String Nationalty = jTable1.getValueAt(row_num, 5 ).toString();
        String Phone = jTable1.getValueAt(row_num, 6 ).toString();
        String gender = jTable1.getValueAt(row_num, 7 ).toString();
        String email = jTable1.getValueAt(row_num, 8 ).toString();
        String ID_Room = jTable1.getValueAt(row_num, 9 ).toString();
        String Room_no = jTable1.getValueAt(row_num, 10 ).toString();
        
        
        jIno.setText(id);
        jFname.setText(first_name);
        jLname.setText(last_name);
        jItype.setSelectedItem(ID_Type);
        jAddress.setText(address);
        jNationalty.setText(Nationalty);
        jPhone.setText(Phone);
        jGender.setSelectedItem(gender);
        jEmail.setText(email);
        jTextField1.setText(ID_Room);
        jRoomNo.setText(Room_no);
        
        
        
       
       
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jTextField1.setText(jRoomNo.getText());
        try{
            jSpinner1.commitEdit();
        }
        catch(java.text.ParseException e){}
        
        double charge;
         int x= (int) jSpinner1.getValue();
         double ch1 = Double.parseDouble(jTextField8.getText());
         double ch2 = Double.parseDouble(jTextField15.getText());
         double ch3 = Double.parseDouble(jTextField13.getText());
       // double ch = String.t
        
        if(ch1 == 0 && ch2 == 0 && ch3 == 0)
        {
        
         if(jroomtype.getSelectedItem().equals("Single")){
            jperiod.setText("250");
           
            charge = x*250;
            String str = Double.toString(charge);
           jTextField10.setText(str);
           jTextField14.setText(str);
           jtotal.setText(str);
           jTextField11.setText(str);
         }
        else if(jroomtype.getSelectedItem().equals("Double")){
            jperiod.setText("300");
            charge = x*300;
            String str = Double.toString(charge);
           jTextField10.setText(str);
           jTextField14.setText(str);
           jtotal.setText(str);
           jTextField11.setText(str);
        }
        }
        
        
        else {
            if(jroomtype.getSelectedItem().equals("Single")){
            jperiod.setText("250");
            charge = x*250;
            String str = Double.toString(charge);
            jTextField10.setText(str);
            charge = charge +ch1;
            str = Double.toString(charge);
            jTextField14.setText(str);
            charge = charge - (charge*(ch2/100));
            str = Double.toString(charge);
           jtotal.setText(str);
           charge =  charge -ch3;
           str = Double.toString(charge);
           jTextField11.setText(str);
         }
        
        else {
            jperiod.setText("300");
            charge = x*300;
            String str = Double.toString(charge);
            jTextField10.setText(str);
            charge = charge +ch1;
            str = Double.toString(charge);
            jTextField14.setText(str);
            charge = charge - (charge*(ch2/100));
            str = Double.toString(charge);
           jtotal.setText(str);
           charge =  charge -ch3;
           str = Double.toString(charge);
           jTextField11.setText(str);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("update guest_information set id_no=?,first_name=?,last_name=?,id_type=?,addrass=?,nationalty=?,phone=?,gender=?,Email=?,ID_room=? where Room_no=?");
            
        String id = jIno.getText();
        String first_name = jFname.getText();
        String last_name = jLname.getText();
        String ID_Type =  (String) jItype.getSelectedItem();            
        String address = jAddress.getText();
        String Nationalty = jNationalty.getText();
        String Phone = jPhone.getText();
        String gender = (String) jGender.getSelectedItem();
        String email = jEmail.getText();
        String ID_Room = jTextField1.getText();
        String Room_no = jRoomNo.getText(); 
        
        stmt.setString(1, id);
        stmt.setString(2, first_name);
        stmt.setString(3, last_name);
        stmt.setString(4, ID_Type);
        stmt.setString(5, address);
        stmt.setString(6, Nationalty);
        stmt.setString(7, Phone);    
        stmt.setString(8, gender);
        stmt.setString(9, email);
        stmt.setString(10, ID_Room);    
        stmt.setString(11, Room_no);
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "IS DONE");
        
        jIno.setText("");
        jFname.setText("");
        jLname.setText("");
        jItype.setSelectedItem("");
        jAddress.setText("");
        jNationalty.setText("");
        jPhone.setText("");
        jGender.setSelectedItem("");
        //jTextField1.setText("");
        jEmail.setText("");
        //jRoomNo.setText("");
        
            jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
         
         
         try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
           PreparedStatement stmt = con.prepareStatement("update room_information set date_in=?,room_type=?,Date_out=?,no_day=?,no_chiled=? where Room_no=?");
         
        double x1 = (int) jSpinner1.getValue();
        double x2 = (int) jSpinner2.getValue();
        String str = Double.toString(x1);
        String str1 = Double.toString(x2);
        String Room_no = jRoomNo.getText();
        String date_in = jTextField2.getText();
        String room_type = (String) jroomtype.getSelectedItem();
        String Date_out =  jTextField3.getText();        
        String no_day = str;
        String no_chiled = str1;
        
        
        
        stmt.setString(1, date_in);
        stmt.setString(2, room_type);
        stmt.setString(3, Date_out);
        stmt.setString(4, str);
        stmt.setString(5, str1);
        stmt.setString(6, Room_no);
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "IS DONE");
        
        jRoomNo.setText("");
        jTextField2.setText("");
        jroomtype.setSelectedItem("");
        jTextField3.setText("");
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        
        jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
         
         
         try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("update rate_information set rate_period=?,total_charges=?,outher_charges=?,sub_total=?,discount=?,total=?,amount_paid=?,balance=? where ID_room=?");
          
            
        String rate_period = jperiod.getText();
        String total_charges = jTextField10.getText();
        String outher_charges = jTextField8.getText();
        String sub_total =  jTextField14.getText();            
        String discount = jTextField15.getText();
        String total = jtotal.getText();
        String amount_paid = jTextField13.getText();
        String balance = (String) jTextField11.getText();
        String ID_room = jTextField1.getText();
        
        
        
        stmt.setString(1, rate_period);
        stmt.setString(2, total_charges);
        stmt.setString(3, outher_charges);
        stmt.setString(4, sub_total);
        stmt.setString(5, discount);
        stmt.setString(6, total);    
        stmt.setString(7, amount_paid);
        stmt.setString(8, balance);
        stmt.setString(9, ID_room);
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "IS DONE");
        
        jTextField1.setText("");
        jperiod.setText("");
        jTextField10.setText("");
        jTextField8.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jtotal.setText("");
        jTextField13.setText("");
        jTextField11.setText("");
        
            jShowBtnActionPerformed(evt);
            
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
         
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
       
      
        
        int row_num = jTable2.getSelectedRow();
        String Room_no = jTable2.getValueAt(row_num, 0 ).toString();
        String date_in = jTable2.getValueAt(row_num, 1 ).toString();
        String room_type = jTable2.getValueAt(row_num, 2 ).toString();
        String Date_out = jTable2.getValueAt(row_num, 3 ).toString();
        String no_day = jTable2.getValueAt(row_num, 4 ).toString();
        String no_chiled = jTable2.getValueAt(row_num, 5 ).toString();
       
        int x1 = Integer.parseInt(no_day);
        int x2 = Integer.parseInt(no_chiled);
        
        jRoomNo.setText(Room_no);
        jTextField2.setText(date_in);
        jroomtype.setSelectedItem(room_type);
        jTextField3.setText(Date_out);
        jSpinner1.setValue(x1);
        jSpinner2.setValue(x2);
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        
        
        
        int row_num = jTable3.getSelectedRow();
        String ID_room = jTable3.getValueAt(row_num, 0 ).toString();
        String rate_period = jTable3.getValueAt(row_num, 1 ).toString();
        String total_charges = jTable3.getValueAt(row_num, 2 ).toString();
        String outher_charges = jTable3.getValueAt(row_num, 3 ).toString();
        String sub_total = jTable3.getValueAt(row_num, 4 ).toString();
        String discount = jTable3.getValueAt(row_num, 5 ).toString();
        String total = jTable3.getValueAt(row_num, 6 ).toString();
        String amount_paid = jTable3.getValueAt(row_num, 7 ).toString();
        String balance = jTable3.getValueAt(row_num, 8 ).toString();
       
        
        
        jTextField1.setText(ID_room);
        jperiod.setText(rate_period);
        jTextField10.setText(total_charges);
        jTextField8.setText(outher_charges);
        jTextField14.setText(sub_total);
        jTextField15.setText(discount);
        jtotal.setText(total);
        jTextField13.setText(amount_paid);
        jTextField11.setText(balance);
        
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jTextField13.setText(jtotal.getText());
        jTextField11.setText("0.0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from guest_information where ID_Room=?");
            String ID_Room = jTextField1.getText();
            stmt.setString(1, ID_Room);
            
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("id_carde");
             dm.addColumn("first_name");
             dm.addColumn("last_name");
             dm.addColumn("ID_Type");
             dm.addColumn("address");
             dm.addColumn("Nationalty");
             dm.addColumn("Phone");
             dm.addColumn("gender");
             dm.addColumn("email");
             dm.addColumn("ID_Room");
             dm.addColumn("Room_no.");
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8),set.getString(9),set.getString(10),set.getString(11)};
                dm.addRow(r);   
            }
            jTable1.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
         
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from room_information where Room_no=?");
            String Room_no = jTextField1.getText();
            stmt.setString(1, Room_no);
            
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("Room_no");
             dm.addColumn("date_in");
             dm.addColumn("room_type");
             dm.addColumn("Date_out");
             dm.addColumn("no_day");
             dm.addColumn("no_chiled");
             
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);   
            }
            jTable2.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
          try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotalbadawy","root","root");
            PreparedStatement stmt = con.prepareStatement("select * from rate_information where ID_Room=?");
            String ID_Room = jTextField1.getText();
            stmt.setString(1, ID_Room);
            
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
             
             dm.addColumn("ID_room");
             dm.addColumn("rate_period");
             dm.addColumn("total_charges");
             dm.addColumn("outher_charges");
             dm.addColumn("sub_total");
             dm.addColumn("discount");
             dm.addColumn("total");
             dm.addColumn("amount_paid");
             dm.addColumn("balance");
             
            while(set.next()) 
            {
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8),set.getString(9)};
                dm.addRow(r);   
            }
            jTable3.setModel(dm);
        }
        catch (SQLException ex) {
            System.out.println("Erorr! ");
        }
         
         
        
          
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jNationaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNationaltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNationaltyActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jFname;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JTextField jIno;
    private javax.swing.JComboBox<String> jItype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLname;
    private javax.swing.JTextField jNationalty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPhone;
    private javax.swing.JTextField jRoomNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jShowBtn;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jlable;
    private javax.swing.JTextField jperiod;
    private javax.swing.JComboBox<String> jroomtype;
    private javax.swing.JTextField jtotal;
    // End of variables declaration//GEN-END:variables
}